name = "Mine Detector Fixes"
author = "DartRuffian"
prefix = "MDF"
mainprefix = "DA"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_mdf_ca.paa",
    "logo_mdf_over_ca.paa",
    "LICENSE",
    "README.md"
]
exclude = [
    "*.psd"
]

[properties]
author = "DartRuffian"
url = "https://github.com/DartRuffian/Mine-Detector-Fixes"

[hemtt.launch.default]
workshop = [
    "450814997",  # CBA
    "2369477168", # ADT
]
presets = []
dlc = []
optionals = []
parameters = []

[hemtt.launch.jlts]
workshop = [
    "450814997",  # CBA
    "2369477168", # ADT
    "1940589429"  # JLTS
]
presets = []
dlc = []
optionals = []
parameters = []